services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "odoo"
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17.0
    platform: linux/amd64 
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      # - ./kaelo_employee_onboarding:/mnt/extra-addons/kaelo_employee_onboarding
      # - ./sample_data:/mnt/extra-addons/sample_data
    environment:
      DB_HOST: "db"
      DB_USER: "odoo"
      DB_PASSWORD: "odoo"
      DB_NAME: "postgres" 


volumes:
  odoo-web-data:
  odoo-db-data: