version: '3.1'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./kaelo_employee_onboarding:/mnt/extra-addons/kaelo_employee_onboarding
      - ./sample_data:/mnt/extra-addons/sample_data
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
